ARG intersight_base_version=1.0.9-latest
ARG intersight_base_path=dockerhub.cisco.com/cspg-intersight-master-docker/andromeda/intersight-base
FROM ${intersight_base_path}:${intersight_base_version}
ADD spewer /spewer
CMD ["/spewer"]
